### ISSUE TITLE
Adapter微调报错

### ISSUE THREAD

**Issue by XinzheGeng** [OpenGVLab/InternVL-MMDetSeg#1]
作者你好，我已经按照[安装步骤](https://github.com/OpenGVLab/InternVL-MMDetSeg?tab=readme-ov-file#installation)搭建了环境，但在ADE20K复现InternViT-6B-Adapter时遇到了deepspeed报错的问题，似乎是该版本不兼容：

> /root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
> and will be removed in future. Use torchrun.
> Note that --use_env is set by default in torchrun.
> If your script expects `--local_rank` argument to be set, please
> change it to read from `os.environ['LOCAL_RANK']` instead. See 
> https://pytorch.org/docs/stable/distributed.html#launch-utility for 
> further instructions
> 
>   warnings.warn(
> /mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
>   warnings.warn(
> /root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/pydantic/_internal/_config.py:322: UserWarning: Valid config keys have changed in V2:
> * 'allow_population_by_field_name' has been renamed to 'populate_by_name'
> * 'validate_all' has been renamed to 'validate_default'
>   warnings.warn(message, UserWarning)
> /root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/pydantic/_internal/_fields.py:151: UserWarning: Field "model_persistence_threshold" has conflict with protected namespace "model_".
> 
> You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
>   warnings.warn(
> /root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/pydantic/_internal/_config.py:322: UserWarning: Valid config keys have changed in V2:
> * 'validate_all' has been renamed to 'validate_default'
>   warnings.warn(message, UserWarning)
> Traceback (most recent call last):
>   File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmsegmentation/tools/train.py", line 12, in <module>
>     from mmcv.cnn.utils import revert_sync_batchnorm
>   File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/cnn/__init__.py", line 14, in <module>
>     from .builder import MODELS, build_model_from_cfg
>   File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/cnn/builder.py", line 2, in <module>
>     from ..runner import Sequential
>   File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/runner/__init__.py", line 3, in <module>
>     from .base_runner import BaseRunner
>   File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/runner/base_runner.py", line 14, in <module>
>     import deepspeed
>   File "/root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/deepspeed/__init__.py", line 17, in <module>
>     from .runtime.engine import DeepSpeedEngine, DeepSpeedOptimizerCallable, DeepSpeedSchedulerCallable
>   File "/root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 93, in <module>
>     from deepspeed.inference.config import DtypeEnum
>   File "/root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/deepspeed/inference/config.py", line 88, in <module>
>     class BaseQuantConfig(DeepSpeedConfigModel):
>   File "/root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 92, in __new__
>     private_attributes = inspect_namespace(
>   File "/root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 384, in inspect_namespace
>     raise PydanticUserError(
> pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `enabled = True`. All model fields require a type annotation; if `enabled` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

然后我将deepspeed版本换到了最新版，这个报错就没有了，但是又出现了新的问题，MSDeformAttn没有成功安装：

> [2024-03-20 08:33:25,013] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
> Please install MSDeformAttn if you want to use ViT-Adapter
> Please install MSDeformAttn if you want to use ViT-Adapter
> Please install MSDeformAttn if you want to use ViT-Adapter
> 2024-03-20 08:33:29,409 - mmseg - INFO - Multi-processing start method is `None`
> 2024-03-20 08:33:29,410 - mmseg - INFO - OpenCV num_threads is `128
> 2024-03-20 08:33:29,463 - mmseg - INFO - Environment info:

> ...
> 2024-03-20 08:34:52,731 - mmseg - INFO - _IncompatibleKeys(missing_keys=[], unexpected_keys=['clip_projector.norm1_q.weight', 'clip_projector.norm1_q.bias', 'clip_projector.norm1_k.weight', 'clip_projector.norm1_k.bias', 'clip_projector.norm1_v.weight', 'clip_projector.norm1_v.bias', 'clip_projector.cross_attn.q_bias', 'clip_projector.cross_attn.k_bias', 'clip_projector.cross_attn.v_bias', 'clip_projector.cross_attn.q.weight', 'clip_projector.cross_attn.k.weight', 'clip_projector.cross_attn.v.weight', 'clip_projector.cross_attn.proj.weight', 'clip_projector.cross_attn.proj.bias'])
> INFO:mmseg:_IncompatibleKeys(missing_keys=[], unexpected_keys=['clip_projector.norm1_q.weight', 'clip_projector.norm1_q.bias', 'clip_projector.norm1_k.weight', 'clip_projector.norm1_k.bias', 'clip_projector.norm1_v.weight', 'clip_projector.norm1_v.bias', 'clip_projector.cross_attn.q_bias', 'clip_projector.cross_attn.k_bias', 'clip_projector.cross_attn.v_bias', 'clip_projector.cross_attn.q.weight', 'clip_projector.cross_attn.k.weight', 'clip_projector.cross_attn.v.weight', 'clip_projector.cross_attn.proj.weight', 'clip_projector.cross_attn.proj.bias'])
> Traceback (most recent call last):
>   File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/utils/registry.py", line 69, in build_from_cfg
>     return obj_cls(**args)
>   File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmsegmentation/mmseg/models/backbones/vit_adapter.py", line 49, in __init__
>     self.interactions = nn.Sequential(*[
>   File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmsegmentation/mmseg/models/backbones/vit_adapter.py", line 50, in <listcomp>
>     InteractionBlock(dim=embed_dim, num_heads=deform_num_heads, n_points=n_points,
>   File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmsegmentation/mmseg/models/backbones/adapter_modules.py", line 165, in __init__
>     self.injector = Injector(dim=dim, n_levels=3, num_heads=num_heads, init_values=init_values,
>   File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmsegmentation/mmseg/models/backbones/adapter_modules.py", line 138, in __init__
>     self.attn = MSDeformAttn(d_model=dim, n_levels=n_levels, n_heads=num_heads,
> NameError: name 'MSDeformAttn' is not defined
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/utils/registry.py", line 69, in build_from_cfg
>     return obj_cls(**args)
>   File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmsegmentation/mmseg/models/segmentors/encoder_decoder.py", line 36, in __init__
>     self.backbone = builder.build_backbone(backbone)
>   File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmsegmentation/mmseg/models/builder.py", line 23, in build_backbone
>     return BACKBONES.build(cfg)
>   File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/utils/registry.py", line 237, in build
>     return self.build_func(*args, **kwargs, registry=self)
>   File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
>     return build_from_cfg(cfg, registry, default_args)
>   File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/utils/registry.py", line 72, in build_from_cfg
>     raise type(e)(f'{obj_cls.__name__}: {e}')
> NameError: InternViTAdapter: name 'MSDeformAttn' is not defined
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmsegmentation/tools/train.py", line 246, in <module>
>     main()
>   File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmsegmentation/tools/train.py", line 199, in main
>     model = build_segmentor(
>   File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmsegmentation/mmseg/models/builder.py", line 51, in build_segmentor
>     return SEGMENTORS.build(
>   File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/utils/registry.py", line 237, in build
>     return self.build_func(*args, **kwargs, registry=self)
>   File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
>     return build_from_cfg(cfg, registry, default_args)
>   File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/utils/registry.py", line 72, in build_from_cfg
>     raise type(e)(f'{obj_cls.__name__}: {e}')
> NameError: EncoderDecoder: InternViTAdapter: name 'MSDeformAttn' is not define

请问该如何解决？这是否和我更改了deepspeed版本有关？

**Comment by czczup** [comment]
您好，这个问题看着是deformable_attention没有编译；README的步骤里忘了写要手动编译deformable_attention了，您可以执行这个文件编译一下：https://github.com/OpenGVLab/InternVL-MMDetSeg/blob/main/ops/compile.sh

**Comment by XinzheGeng** [comment]
> 您好，这个问题看着是deformable_attention没有编译；README的步骤里忘了写要手动编译deformable_attention了，您可以执行这个文件编译一下：https://github.com/OpenGVLab/InternVL-MMDetSeg/blob/main/ops/compile.sh

您好，我按您给的方法编译成功了deformable_attention，还是有同样的报错，但是Please install MSDeformAttn if you want to use ViT-Adapter这句比之前少了一行，之前是会弹出三行，这次是两行。
[2024-03-27 06:01:25,093] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Please install MSDeformAttn if you want to use ViT-Adapter
Please install MSDeformAttn if you want to use ViT-Adapter
2024-03-27 06:01:30,151 - mmseg - INFO - Multi-processing start method is `None`
2024-03-27 06:01:30,154 - mmseg - INFO - OpenCV num_threads is `128
2024-03-27 06:01:30,228 - mmseg - INFO - Environment info:

后面的报错和之前一样的，定位后看到是adapter_modules.py和vit_adapter.py这两个文件依然找不到这个模块：
Traceback (most recent call last):
  File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmsegmentation/mmseg/models/backbones/vit_adapter.py", line 49, in __init__
    self.interactions = nn.Sequential(*[
  File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmsegmentation/mmseg/models/backbones/vit_adapter.py", line 50, in <listcomp>
    InteractionBlock(dim=embed_dim, num_heads=deform_num_heads, n_points=n_points,
  File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmsegmentation/mmseg/models/backbones/adapter_modules.py", line 165, in __init__
    self.injector = Injector(dim=dim, n_levels=3, num_heads=num_heads, init_values=init_values,
  File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmsegmentation/mmseg/models/backbones/adapter_modules.py", line 138, in __init__
    self.attn = MSDeformAttn(d_model=dim, n_levels=n_levels, n_heads=num_heads,
NameError: name 'MSDeformAttn' is not defined

**Comment by czczup** [comment]
您试试把ops文件夹软连接到mmsegmentation文件夹下
```sh
cd mmsegmentation/
ln -s ../ops ./
```

**Comment by XinzheGeng** [comment]
> 您试试把ops文件夹软连接到mmsegmentation文件夹下
> 
> ```shell
> cd mmsegmentation/
> ln -s ../ops ./
> ```
感谢答复，这个问题已经解决了，但是后面在deepspeed出现了另外的报错，不确定是不是因为我之前更换了版本：
![image](https://github.com/OpenGVLab/InternVL-MMDetSeg/assets/46108309/deadee08-7817-4129-beb0-9bedef97dc8a)
我尝试了不使用deepspeed，在config中改了deepspeed=false后，又出现了如下报错：
![image](https://github.com/OpenGVLab/InternVL-MMDetSeg/assets/46108309/4106a1b6-8440-4f30-910a-f4803029ba13)

**Comment by czczup** [comment]
deepspeed新版应该是不兼容的，我有尝试过，您可以退回0.8.0再试试看

**Comment by XinzheGeng** [comment]
Traceback (most recent call last):
  File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmsegmentation/tools/train.py", line 12, in <module>
    from mmcv.cnn.utils import revert_sync_batchnorm
  File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/cnn/__init__.py", line 14, in <module>
    from .builder import MODELS, build_model_from_cfg
  File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/cnn/builder.py", line 2, in <module>
    from ..runner import Sequential
  File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/runner/__init__.py", line 3, in <module>
    from .base_runner import BaseRunner
  File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/runner/base_runner.py", line 14, in <module>
    import deepspeed
  File "/root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/deepspeed/__init__.py", line 17, in <module>
    from .runtime.engine import DeepSpeedEngine, DeepSpeedOptimizerCallable, DeepSpeedSchedulerCallable
  File "/root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 93, in <module>
    from deepspeed.inference.config import DtypeEnum
  File "/root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/deepspeed/inference/config.py", line 88, in <module>
    class BaseQuantConfig(DeepSpeedConfigModel):
  File "/root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 92, in __new__
    private_attributes = inspect_namespace(
  File "/root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 384, in inspect_namespace
    raise PydanticUserError(
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `enabled = True`. All model fields require a type annotation; if `enabled` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

For further information visit https://errors.pydantic.dev/2.6/u/model-field-missing-annotation

**Comment by XinzheGeng** [comment]
> Traceback (most recent call last): File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmsegmentation/tools/train.py", line 12, in from mmcv.cnn.utils import revert_sync_batchnorm File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/cnn/**init**.py", line 14, in from .builder import MODELS, build_model_from_cfg File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/cnn/builder.py", line 2, in from ..runner import Sequential File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/runner/**init**.py", line 3, in from .base_runner import BaseRunner File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/runner/base_runner.py", line 14, in import deepspeed File "/root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/deepspeed/**init**.py", line 17, in from .runtime.engine import DeepSpeedEngine, DeepSpeedOptimizerCallable, DeepSpeedSchedulerCallable File "/root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 93, in from deepspeed.inference.config import DtypeEnum File "/root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/deepspeed/inference/config.py", line 88, in class BaseQuantConfig(DeepSpeedConfigModel): File "/root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 92, in **new** private_attributes = inspect_namespace( File "/root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 384, in inspect_namespace raise PydanticUserError( pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `enabled = True`. All model fields require a type annotation; if `enabled` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.
> 
> For further information visit https://errors.pydantic.dev/2.6/u/model-field-missing-annotation

您好，我退回0.8.0后是这个报错

**Comment by XinzheGeng** [comment]
> > Traceback (most recent call last): File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmsegmentation/tools/train.py", line 12, in from mmcv.cnn.utils import revert_sync_batchnorm File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/cnn/**init**.py", line 14, in from .builder import MODELS, build_model_from_cfg File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/cnn/builder.py", line 2, in from ..runner import Sequential File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/runner/**init**.py", line 3, in from .base_runner import BaseRunner File "/mnt/gengxz/projects/InternVL_MMDetSeg/mmcv/mmcv/runner/base_runner.py", line 14, in import deepspeed File "/root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/deepspeed/**init**.py", line 17, in from .runtime.engine import DeepSpeedEngine, DeepSpeedOptimizerCallable, DeepSpeedSchedulerCallable File "/root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 93, in from deepspeed.inference.config import DtypeEnum File "/root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/deepspeed/inference/config.py", line 88, in class BaseQuantConfig(DeepSpeedConfigModel): File "/root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 92, in **new** private_attributes = inspect_namespace( File "/root/anaconda3/envs/internvl-mmdetseg/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 384, in inspect_namespace raise PydanticUserError( pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `enabled = True`. All model fields require a type annotation; if `enabled` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.
> > For further information visit https://errors.pydantic.dev/2.6/u/model-field-missing-annotation
> 
> 您好，我退回0.8.0后是这个报错

这个问题应该已经解决了，我之前没有使用过deepspeed，麻烦您看一下这个训练日志是正常的吗
![image](https://github.com/OpenGVLab/InternVL-MMDetSeg/assets/46108309/9124d822-c2d7-4266-a9ff-fe44647e7ec1)

**Comment by czczup** [comment]
应该没问题

**Comment by ciderjoy** [comment]
Dear dev, the model weights of mmseg can also be used for mmdet, right? How about updating the weights information in the readme file in mmdet as well? Or update the information in the readme file which at the top level?  It's maybe better for everyone. Thx~

**Comment by ciderjoy** [comment]
> Dear dev, the model weights of mmseg can also be used for mmdet, right? How about updating the weights information in the readme file in mmdet as well? Or update the information in the readme file which at the top level? It's maybe better for everyone. Thx~

I mean download infomation.

**Comment by czczup** [comment]
> > Dear dev, the model weights of mmseg can also be used for mmdet, right? How about updating the weights information in the readme file in mmdet as well? Or update the information in the readme file which at the top level? It's maybe better for everyone. Thx~
> 
> I mean download infomation.

Thanks for your advice~
