### ISSUE TITLE
模型权重保存问题

### ISSUE THREAD

**Issue by XinzheGeng** [OpenGVLab/InternVL-MMDetSeg#3]
作者您好，我使用Adapter微调LoveDA数据集时看到工作目录下是这样的：
![image](https://github.com/OpenGVLab/InternVL-MMDetSeg/assets/46108309/9b286165-0196-4e5e-9a0b-757a7e9f8ef0)
里面只有最新的权重文件，请问mIoU最高的权重是保存到哪里呢，这个是我的config：
![image](https://github.com/OpenGVLab/InternVL-MMDetSeg/assets/46108309/e76cb775-1b5c-4a33-934c-71a0d4a9f796)

**Comment by czczup** [comment]
您好，目前代码这块在开启了deepspeed之后，没有对原本的save_best做兼容，所以不会有best model保存下来。
